version: "2"
services:
  test-app:
    image: rest.juannavas.xyz
    container_name: rest.juannavas.xyz
    volumes:
      - test-storage:/var/www/html/backend/storage
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rest.juannavas.dev"
      - "traefik.port=80"

networks:
  default:
    external:
      name: traefik
volumes:
  test-storage:
